general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    layout = scrolling
}


decoration {
    # Use round window corners
    rounding = 8
}

scrolling {
  fullscreen_on_one_column = true
}
